
---Create Cleaned COMPLAINTS Table
CREATE OR REPLACE TABLE COMPLAINTS AS

SELECT
    TRY_TO_NUMBER(COMPLAINT_ID) AS COMPLAINT_ID,
    TRY_TO_DATE(DATE_RECEIVED) AS DATE_RECEIVED,
    TRIM(PRODUCT) AS PRODUCT,
    TRIM(ISSUE) AS ISSUE,
    TRIM(COMPANY) AS COMPANY,
    COALESCE(TRIM(STATE),'UNKNOWN') AS STATE,
    COALESCE(CONSUMER_COMPLAINT_NARRATIVE, 'NO NARRATIVE PROVIDED') AS COMPLAINT_NARRATIVE,
    TRIM(SUBMITTED_VIA) AS SUBMITTED_VIA,
    TRIM(TIMELY_RESPONSE) AS TIMELY_RESPONSE,
    TRIM(CONSUMER_DISPUTED) AS CONSUMER_DISPUTED
FROM RAW_COMPLAINTS;
