dbt_AI_financial_risk_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"                      # Replace with your Snowflake Account Identifier (e.g., xy12345.us-east-1)
      user: "{{ env_var('SNOWFLAKE_USER') }}"                            # Your Snowflake username
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"                     # Your Snowflake password
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"                          # Running under Accountadmin or your custom pipeline role
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"                    # The dedicated compute engine created in DDL script 1
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"                 # The main platform analytics database
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"                              # The default landing target schema for your staging models
      threads: 4                                  # Allows up to 4 modeling tasks to compile concurrently
      client_session_keep_alive: False