CREATE OR REPLACE TABLE RISK_ANALYSIS
(    COMPLAINT_ID NUMBER,
    RISK_CATEGORY STRING,
    SENTIMENT STRING,
    RISK_SCORE STRING,
    AI_SUMMARY STRING,
    COMPLIANCE_INSIGHT STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);


DESC TABLE RISK_ANALYSIS;
