--use database and schema
USE DATABASE FINANCIAL_RISK_INTELLIGENCE;
USE SCHEMA ANALYTICS;

-- Create Raw Table
-- Using STRING as data type is a classic strategy when you are building what data engineers call a Landing Table (or "Raw" table).
-- do not adding primary key or any other CONSTRAINT because this raw data.
CREATE OR REPLACE TABLE RAW_COMPLAINTS
(
    DATE_RECEIVED STRING,
    PRODUCT STRING,
    SUB_PRODUCT STRING,
    ISSUE STRING,
    SUB_ISSUE STRING,
    CONSUMER_COMPLAINT_NARRATIVE STRING,
    COMPANY_PUBLIC_RESPONSE STRING,
    COMPANY STRING,
    STATE STRING,
    ZIP_CODE STRING,
    TAGS STRING,
    CONSUMER_CONSENT_PROVIDED STRING,
    SUBMITTED_VIA STRING,
    DATE_SENT_TO_COMPANY STRING,
    COMPANY_RESPONSE_TO_CONSUMER STRING,
    TIMELY_RESPONSE STRING,
    CONSUMER_DISPUTED STRING,
    COMPLAINT_ID STRING
);
