---use database----
USE DATABASE FINANCIAL_RISK_INTELLIGENCE;

----use schema----
USE SCHEMA ANALYTICS;

----create table----
CREATE OR REPLACE TABLE COMPLAINTS (
    COMPLAINT_ID NUMBER,
    DATE_RECEIVED DATE,
    PRODUCT STRING,
    ISSUE STRING,
    COMPANY STRING,
    STATE STRING,
    COMPLAINT_NARRATIVE STRING
);
